# Generated by Django 3.0.3 on 2020-07-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carcharger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_company', models.CharField(max_length=200)),
                ('car_name', models.CharField(max_length=200)),
                ('dc', models.BinaryField(max_length=1)),
                ('ac', models.BinaryField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='carcharger',
            name='ac',
        ),
        migrations.RemoveField(
            model_name='carcharger',
            name='car_company',
        ),
        migrations.RemoveField(
            model_name='carcharger',
            name='dc',
        ),
        migrations.AddField(
            model_name='carcharger',
            name='car_chger_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
