# Generated by Django 3.0.3 on 2020-07-21 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dong',
        ),
    ]
